/*
data = [
  {
    name: 'Aatrox',
    tag:  ['Fighter', 'Tank'],
    stats: {
      hp: 537.8,
      hpperlevel: 85,
      mp: 105.6,
      mpperlevel: 45,
      movespeed: 345,
      armor: 24.384,
      armorperlevel: 3.8,
      spellblock: 32.1,
      spellblockperlevel: 1.25,
      attackrange: 150,
      hpregen: 6.59,
      hpregenperlevel: 0.5,
      mpregen: 0,
      mpregenperlevel: 0,
      crit: 0,
      critperlevel: 0,
      attackdamage: 60.376,
      attackdamageperlevel: 3.2,
      attackspeedoffset: -0.04,
      attackspeedperlevel: 3,
    },
  },
  {
    name: 'Ahri',
    tag: ['Mage', 'Assassin'],
    stats: {
      hp: 514.4,
      hpperlevel: 80,
      mp: 334,
      mpperlevel: 50,
      movespeed: 330,
      armor: 20.88,
      armorperlevel: 3.5,
      spellblock: 30,
      spellblockperlevel: 0,
      attackrange: 550,
      hpregen: 6.505,
      hpregenperlevel: 0.6,
      mpregen: 6,
      mpregenperlevel: 0.8,
      crit: 0,
      critperlevel: 0,
      attackdamage: 53.04,
      attackdamageperlevel: 3,
      attackspeedoffset: -0.065,
      attackspeedperlevel: 2,
    },
     
    name: 'Akali',
    tag:  ['Assassin'],
    stats: {
        hp: 587.8,
        hpperlevel: 85,
        mp: 200,
        mpperlevel: 0,
        movespeed: 350,
        armor: 26.38,
        armorperlevel: 3.5,
        spellblock: 32.1,
        spellblockperlevel: 1.25,
        attackrange: 125,
        hpregen: 8.34,
        hpregenperlevel: 0.65,
        mpregen: 50,
        mpregenperlevel: 0,
        crit: 0,
        critperlevel: 0,
        attackdamage: 58.376,
        attackdamageperlevel: 3.2,
        attackspeedoffset: -0.1,
        attackspeedperlevel: 3.1,
    },
  },
];
*/
 
